"""Optional LLM clients for ResearchFlow.

The package must remain runnable without API keys. LLM clients therefore fail
closed: they raise LLMError and the pipeline falls back to deterministic rules.
"""

from __future__ import annotations

import json
import os
import re
import urllib.error
import urllib.request
from dataclasses import dataclass
from typing import Any, Protocol

from .env import load_local_env


DEFAULT_DEEPSEEK_MODEL = "deepseek-v4-flash"
DEEPSEEK_CHAT_COMPLETIONS_URL = "https://api.deepseek.com/chat/completions"


class LLMError(RuntimeError):
    """Raised when an optional LLM call cannot produce a trusted result."""


class LLMClient(Protocol):
    provider: str

    def generate_json(self, system_prompt: str, user_payload: dict[str, Any]) -> dict[str, Any]:
        """Return a JSON object generated by the model."""


@dataclass(slots=True)
class NoopLLMClient:
    provider: str = "off"

    def generate_json(self, system_prompt: str, user_payload: dict[str, Any]) -> dict[str, Any]:
        raise LLMError("LLM provider is disabled.")


@dataclass(slots=True)
class DeepSeekClient:
    api_key: str | None = None
    model: str | None = None
    timeout: float | None = None
    provider: str = "deepseek"

    def __post_init__(self) -> None:
        load_local_env()
        self.api_key = self.api_key or os.environ.get("DEEPSEEK_API_KEY")
        self.model = self.model or os.environ.get("RESEARCHFLOW_MODEL", DEFAULT_DEEPSEEK_MODEL)
        self.timeout = self.timeout or float(os.environ.get("RESEARCHFLOW_LLM_TIMEOUT", "30"))

    def generate_json(self, system_prompt: str, user_payload: dict[str, Any]) -> dict[str, Any]:
        if not self.api_key:
            raise LLMError("DEEPSEEK_API_KEY is not configured.")

        body = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {
                    "role": "user",
                    "content": json.dumps(user_payload, ensure_ascii=False),
                },
            ],
            "stream": False,
            "response_format": {"type": "json_object"},
        }
        request = urllib.request.Request(
            DEEPSEEK_CHAT_COMPLETIONS_URL,
            data=json.dumps(body, ensure_ascii=False).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
                "User-Agent": "ResearchFlow/0.1",
            },
            method="POST",
        )

        try:
            with urllib.request.urlopen(request, timeout=self.timeout) as response:
                payload = json.loads(response.read().decode("utf-8"))
        except (OSError, urllib.error.URLError, json.JSONDecodeError) as exc:
            raise LLMError(f"DeepSeek request failed: {exc}") from exc

        try:
            content = payload["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError) as exc:
            raise LLMError("DeepSeek response did not contain message content.") from exc

        return parse_json_object(content)


def parse_json_object(content: str) -> dict[str, Any]:
    """Parse a JSON object from plain text or a fenced code block."""

    text = content.strip()
    fence = re.search(r"```(?:json)?\s*(.*?)```", text, flags=re.DOTALL | re.IGNORECASE)
    if fence:
        text = fence.group(1).strip()

    try:
        value = json.loads(text)
    except json.JSONDecodeError as exc:
        raise LLMError(f"LLM output is not valid JSON: {exc}") from exc

    if not isinstance(value, dict):
        raise LLMError("LLM output must be a JSON object.")
    return value


def build_llm_client(provider: str) -> LLMClient:
    if provider == "deepseek":
        return DeepSeekClient()
    return NoopLLMClient()
