"""Markdown report generation."""

from __future__ import annotations

from collections import defaultdict
from datetime import UTC, datetime
from typing import Any

from .models import CitationCheck, ClaimRecord, EvidenceItem, PaperRecord


def render_report(
    topic: str,
    selected_papers: list[PaperRecord],
    evidence_items: list[EvidenceItem],
    claims: list[ClaimRecord],
    citation_checks: list[CitationCheck],
    query_plan: list[Any] | None = None,
    actual_source: str = "",
    fallback_reason: str = "",
    llm_provider: str = "off",
    llm_used: bool = False,
) -> str:
    evidence_by_paper: dict[str, list[EvidenceItem]] = defaultdict(list)
    for item in evidence_items:
        evidence_by_paper[item.paper_id].append(item)

    check_by_paper = {check.paper_id: check for check in citation_checks}
    generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    query_plan = query_plan or []
    source_label = actual_source or "unknown"
    top_sources = ", ".join(sorted({paper.source for paper in selected_papers})) or source_label
    total_evidence = len(evidence_items)

    lines: list[str] = [
        f"# Literature Review: {topic}",
        "",
        "## Executive Summary",
        "",
        (
            f"ResearchFlow generated this literature review on {generated_at}. "
            f"The agent searched `{source_label}` sources, selected {len(selected_papers)} "
            f"core papers, extracted {total_evidence} evidence items, and linked "
            f"{len(claims)} synthesis claims back to retrieved sources."
        ),
        "",
        (
            f"Selected source coverage: {top_sources}. "
            f"LLM mode: {llm_provider}; LLM used: {str(llm_used).lower()}."
        ),
    ]
    if fallback_reason:
        lines.extend(["", f"Fallback note: {fallback_reason}"])
    lines.extend(
        [
            "",
            "## Search Method and Scope",
            "",
            (
                "The agent follows a traceable workflow: query planning, live paper search, "
                "ranking, evidence extraction, claim synthesis, citation checking, and report writing."
            ),
            "",
        ]
    )
    if query_plan:
        lines.append("| Query ID | Search Query | Source Intent |")
        lines.append("| --- | --- | --- |")
        for query in query_plan:
            query_id = getattr(query, "query_id", "")
            query_text = getattr(query, "query_text", "")
            source = getattr(query, "source", "")
            lines.append(f"| `{query_id}` | {query_text} | {source} |")
        lines.append("")
    lines.extend(
        [
            "## 1. Research Background",
            "",
            (
                "This report is generated by ResearchFlow as a first-pass literature survey. "
                "It emphasizes source traceability: every major synthesis claim points back "
                "to evidence extracted from the selected papers, and each reference comes "
                "from the retrieved paper set."
            ),
            "",
            "## 2. Core Papers",
            "",
        ]
    )

    for index, paper in enumerate(selected_papers, start=1):
        check = check_by_paper.get(paper.paper_id)
        status = check.status if check else "warning"
        lines.extend(
            [
                f"### P{index}. {paper.title}",
                "",
                f"- Authors: {', '.join(paper.authors)}",
                f"- Year: {paper.year}",
                f"- Source: {paper.source}",
                f"- URL: {paper.url}",
                f"- Citations: {paper.citation_count}",
                f"- Citation check: {status}",
                f"- Summary: {paper.abstract}",
                "",
            ]
        )

    lines.extend(["## 3. Key Claims and Evidence", ""])
    if claims:
        lines.append("| Claim ID | Type | Claim | Evidence IDs |")
        lines.append("| --- | --- | --- | --- |")
        for claim in claims:
            evidence_refs = ", ".join(f"`{item}`" for item in claim.evidence_ids) or "None"
            lines.append(
                f"| `{claim.claim_id}` | {claim.claim_type} | {claim.claim_text} | {evidence_refs} |"
            )
        lines.append("")
    else:
        lines.extend(["No claims were generated.", ""])

    lines.extend(["## 4. Method Taxonomy", ""])
    grouped: dict[str, list[EvidenceItem]] = defaultdict(list)
    for item in evidence_items:
        grouped[item.category].append(item)
    for category, items in grouped.items():
        lines.append(f"### {category.replace('_', ' ').title()}")
        lines.append("")
        for item in items[:5]:
            lines.append(f"- {item.claim} (`{item.evidence_id}`)")
        lines.append("")

    lines.extend(["## Evidence Ledger", ""])
    lines.append("| Evidence ID | Paper ID | Category | Confidence | Support Text |")
    lines.append("| --- | --- | --- | ---: | --- |")
    for item in evidence_items:
        support = item.support_text.replace("|", "\\|")
        if len(support) > 280:
            support = support[:277].rstrip() + "..."
        lines.append(
            f"| `{item.evidence_id}` | `{item.paper_id}` | {item.category} | "
            f"{item.confidence:.2f} | {support} |"
        )
    lines.append("")

    lines.extend(["## 5. Comparative Analysis", ""])
    lines.append("| Paper | Main Evidence | Confidence |")
    lines.append("| --- | --- | --- |")
    for paper in selected_papers:
        items = evidence_by_paper.get(paper.paper_id, [])
        if not items:
            continue
        evidence = items[0]
        lines.append(f"| {paper.title} | {evidence.claim} | {evidence.confidence:.2f} |")
    lines.append("")

    lines.extend(["## 6. Research Gaps", ""])
    gap_claims = [claim for claim in claims if claim.claim_type == "Hypothesis"]
    if gap_claims:
        for claim in gap_claims:
            evidence_refs = ", ".join(f"`{item}`" for item in claim.evidence_ids)
            lines.append(f"- {claim.claim_text} Evidence: {evidence_refs}")
    else:
        lines.append("- More full-text evidence is needed before making strong gap claims.")
    lines.append("")

    lines.extend(["## 7. Limitations of This Automated Review", ""])
    lines.extend(
        [
            "- MVP mode may rely on metadata and abstracts rather than full paper text.",
            "- Offline fixture mode is deterministic and intended for demo stability.",
            "- Citation checks validate metadata availability, not peer-review quality.",
            "",
        ]
    )

    lines.extend(["## Citation Checks", ""])
    lines.append("| Check ID | Paper ID | Status | Message |")
    lines.append("| --- | --- | --- | --- |")
    for check in citation_checks:
        lines.append(f"| `{check.check_id}` | `{check.paper_id}` | {check.status} | {check.message} |")
    lines.append("")

    lines.extend(["## References", ""])
    for index, paper in enumerate(selected_papers, start=1):
        authors = ", ".join(paper.authors)
        lines.append(f"[P{index}] {authors}. ({paper.year}). {paper.title}. {paper.url}")

    return "\n".join(lines) + "\n"
