"""Markdown report generation."""

from __future__ import annotations

from collections import defaultdict
from datetime import UTC, datetime
import re
from typing import Any

from .models import CitationCheck, ClaimRecord, EvidenceItem, PaperRecord


def _clip_table_text(value: str, max_length: int = 160) -> str:
    text = " ".join(_sanitize_secret_text(value).replace("|", "\\|").split())
    if len(text) <= max_length:
        return text
    return text[: max_length - 3].rstrip() + "..."


def _sanitize_secret_text(value: Any) -> str:
    text = str(value)
    text = re.sub(r"sk-[A-Za-z0-9]+", "[REDACTED_API_KEY]", text)
    text = text.replace("DEEPSEEK_API_KEY", "[REDACTED_ENV_VAR]")
    return text


def render_report(
    topic: str,
    selected_papers: list[PaperRecord],
    evidence_items: list[EvidenceItem],
    claims: list[ClaimRecord],
    citation_checks: list[CitationCheck],
    query_plan: list[Any] | None = None,
    actual_source: str = "",
    fallback_reason: str = "",
    llm_provider: str = "off",
    llm_used: bool = False,
) -> str:
    evidence_by_paper: dict[str, list[EvidenceItem]] = defaultdict(list)
    for item in evidence_items:
        evidence_by_paper[item.paper_id].append(item)

    check_by_paper = {check.paper_id: check for check in citation_checks}
    generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
    query_plan = query_plan or []
    source_label = actual_source or "unknown"
    top_sources = ", ".join(sorted({paper.source for paper in selected_papers})) or source_label
    total_evidence = len(evidence_items)

    lines: list[str] = [
        f"# Literature Review: {topic}",
        "",
        "## Executive Summary",
        "",
        (
            f"ResearchFlow generated this literature review on {generated_at}. "
            f"The agent searched `{source_label}` sources, selected {len(selected_papers)} "
            f"core papers, extracted {total_evidence} evidence items, and linked "
            f"{len(claims)} synthesis claims back to retrieved sources."
        ),
        "",
        (
            f"Selected source coverage: {top_sources}. "
            f"LLM mode: {llm_provider}; LLM used: {str(llm_used).lower()}."
        ),
    ]
    if fallback_reason:
        lines.extend(["", f"Fallback note: {fallback_reason}"])
    lines.extend(
        [
            "",
            "## Search Method and Scope",
            "",
            (
                "The agent follows a traceable workflow: query planning, live paper search, "
                "ranking, evidence extraction, claim synthesis, citation checking, and report writing."
            ),
            "",
        ]
    )
    if query_plan:
        lines.append("| Query ID | Search Query | Source Intent |")
        lines.append("| --- | --- | --- |")
        for query in query_plan:
            query_id = getattr(query, "query_id", "")
            query_text = getattr(query, "query_text", "")
            source = getattr(query, "source", "")
            lines.append(f"| `{query_id}` | {query_text} | {source} |")
        lines.append("")
    lines.extend(
        [
            "## 1. Research Background",
            "",
            (
                "This report is generated by ResearchFlow as a first-pass literature survey. "
                "It emphasizes source traceability: every major synthesis claim points back "
                "to evidence extracted from the selected papers, and each reference comes "
                "from the retrieved paper set."
            ),
            "",
            "## 2. Core Papers",
            "",
        ]
    )

    for index, paper in enumerate(selected_papers, start=1):
        check = check_by_paper.get(paper.paper_id)
        status = check.status if check else "warning"
        lines.extend(
            [
                f"### P{index}. {paper.title}",
                "",
                f"- Authors: {', '.join(paper.authors)}",
                f"- Year: {paper.year}",
                f"- Source: {paper.source}",
                f"- URL: {paper.url}",
                f"- Citations: {paper.citation_count}",
                f"- Citation check: {status}",
                f"- Summary: {paper.abstract}",
                "",
            ]
        )

    lines.extend(["## 3. Key Claims and Evidence", ""])
    if claims:
        lines.append("| Claim ID | Type | Claim | Evidence IDs |")
        lines.append("| --- | --- | --- | --- |")
        for claim in claims:
            evidence_refs = ", ".join(f"`{item}`" for item in claim.evidence_ids) or "None"
            lines.append(
                f"| `{claim.claim_id}` | {claim.claim_type} | {claim.claim_text} | {evidence_refs} |"
            )
        lines.append("")
    else:
        lines.extend(["No claims were generated.", ""])

    lines.extend(["## 4. Method Taxonomy", ""])
    grouped: dict[str, list[EvidenceItem]] = defaultdict(list)
    for item in evidence_items:
        grouped[item.category].append(item)
    for category, items in grouped.items():
        lines.append(f"### {category.replace('_', ' ').title()}")
        lines.append("")
        for item in items[:5]:
            lines.append(f"- {item.claim} (`{item.evidence_id}`)")
        lines.append("")

    lines.extend(["## Evidence Ledger", ""])
    lines.append("| Evidence ID | Paper ID | Category | Confidence | Support Text |")
    lines.append("| --- | --- | --- | ---: | --- |")
    for item in evidence_items:
        support = item.support_text.replace("|", "\\|")
        if len(support) > 280:
            support = support[:277].rstrip() + "..."
        lines.append(
            f"| `{item.evidence_id}` | `{item.paper_id}` | {item.category} | "
            f"{item.confidence:.2f} | {support} |"
        )
    lines.append("")

    lines.extend(["## 5. Comparative Analysis", ""])
    lines.append("| Paper | Main Evidence | Confidence |")
    lines.append("| --- | --- | --- |")
    for paper in selected_papers:
        items = evidence_by_paper.get(paper.paper_id, [])
        if not items:
            continue
        evidence = items[0]
        lines.append(f"| {paper.title} | {evidence.claim} | {evidence.confidence:.2f} |")
    lines.append("")

    lines.extend(["## 6. Research Gaps", ""])
    gap_claims = [claim for claim in claims if claim.claim_type == "Hypothesis"]
    if gap_claims:
        for claim in gap_claims:
            evidence_refs = ", ".join(f"`{item}`" for item in claim.evidence_ids)
            lines.append(f"- {claim.claim_text} Evidence: {evidence_refs}")
    else:
        lines.append("- More full-text evidence is needed before making strong gap claims.")
    lines.append("")

    lines.extend(["## 7. Limitations of This Automated Review", ""])
    lines.extend(
        [
            "- MVP mode may rely on metadata and abstracts rather than full paper text.",
            "- Offline fixture mode is deterministic and intended for demo stability.",
            "- Citation checks validate metadata availability, not peer-review quality.",
            "",
        ]
    )

    lines.extend(["## Citation Checks", ""])
    lines.append("| Check ID | Paper ID | Status | Message |")
    lines.append("| --- | --- | --- | --- |")
    for check in citation_checks:
        lines.append(f"| `{check.check_id}` | `{check.paper_id}` | {check.status} | {check.message} |")
    lines.append("")

    lines.extend(["## References", ""])
    for index, paper in enumerate(selected_papers, start=1):
        authors = ", ".join(paper.authors)
        lines.append(f"[P{index}] {authors}. ({paper.year}). {paper.title}. {paper.url}")

    return "\n".join(lines) + "\n"


def render_process_markdown(state: dict[str, Any]) -> str:
    """Render an auditable process log without exposing hidden model reasoning."""

    metrics = state.get("metrics", {})
    query_plan = state.get("query_plan", [])
    searched_papers = state.get("searched_papers", [])
    selected_papers = state.get("selected_papers", [])
    evidence_items = state.get("evidence_items", [])
    claims = state.get("claims", [])
    citation_checks = state.get("citation_checks", [])
    node_trace = state.get("node_trace", [])

    source_counts: dict[str, int] = defaultdict(int)
    for paper in searched_papers:
        source_counts[getattr(paper, "source", "unknown")] += 1

    lines: list[str] = [
        f"# Research Process: {state.get('topic', '')}",
        "",
        "This file records observable Agent actions and artifacts. It is not a hidden chain-of-thought transcript.",
        "",
        "## Run Summary",
        "",
        f"- Task ID: `{state.get('task_id', '')}`",
        f"- Requested source: `{state.get('requested_source', '')}`",
        f"- Actual source: `{state.get('actual_source', '')}`",
        f"- Fallback reason: {_sanitize_secret_text(state.get('fallback_reason', '') or 'None')}",
        f"- Report path: `{state.get('report_path', '')}`",
        f"- Graph runtime: `{state.get('graph_runtime', '')}`",
        f"- LLM provider: `{state.get('llm_provider', 'off')}`",
        f"- LLM used: `{str(state.get('llm_used', False)).lower()}`",
        f"- LLM fallback reason: {_sanitize_secret_text(state.get('llm_fallback_reason', '') or 'None')}",
        "",
        "## Query Plan",
        "",
        "| Query ID | Search Query | Source Intent | Filters |",
        "| --- | --- | --- | --- |",
    ]
    for query in query_plan:
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{getattr(query, 'query_id', '')}`",
                    _clip_table_text(getattr(query, "query_text", "")),
                    getattr(query, "source", ""),
                    f"`{getattr(query, 'filters', {})}`",
                ]
            )
            + " |"
        )

    lines.extend(["", "## Search Results", ""])
    lines.append(f"- Retrieved candidates before ranking: {len(searched_papers)}")
    if source_counts:
        lines.append(
            "- Candidate source counts: "
            + ", ".join(f"{source}={count}" for source, count in sorted(source_counts.items()))
        )
    lines.extend(
        [
            "",
            "## Top-K Selection",
            "",
            "Ranking uses topic-term overlap, recency, citation count when available, and duplicate removal.",
            "",
            "| Rank | Paper ID | Title | Year | Source | Score | URL |",
            "| ---: | --- | --- | ---: | --- | ---: | --- |",
        ]
    )
    for index, paper in enumerate(selected_papers, start=1):
        lines.append(
            "| "
            + " | ".join(
                [
                    str(index),
                    f"`{paper.paper_id}`",
                    _clip_table_text(paper.title, 120),
                    str(paper.year),
                    paper.source,
                    f"{paper.score:.3f}",
                    paper.url,
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Evidence Extraction",
            "",
            "| Evidence ID | Paper ID | Category | Confidence | Claim |",
            "| --- | --- | --- | ---: | --- |",
        ]
    )
    for item in evidence_items:
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{item.evidence_id}`",
                    f"`{item.paper_id}`",
                    item.category,
                    f"{item.confidence:.2f}",
                    _clip_table_text(item.claim, 180),
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Claim-Evidence Alignment",
            "",
            "| Claim ID | Type | Claim | Evidence IDs |",
            "| --- | --- | --- | --- |",
        ]
    )
    for claim in claims:
        evidence_refs = ", ".join(f"`{item}`" for item in claim.evidence_ids) or "None"
        lines.append(
            f"| `{claim.claim_id}` | {claim.claim_type} | "
            f"{_clip_table_text(claim.claim_text, 180)} | {evidence_refs} |"
        )

    lines.extend(
        [
            "",
            "## Citation Checks",
            "",
            "| Check ID | Paper ID | Status | Message |",
            "| --- | --- | --- | --- |",
        ]
    )
    for check in citation_checks:
        lines.append(
            f"| `{check.check_id}` | `{check.paper_id}` | {check.status} | "
            f"{_clip_table_text(check.message)} |"
        )

    lines.extend(["", "## Agent Trace", "", "| Step | Node | Status | Output Keys |", "| ---: | --- | --- | --- |"])
    for index, step in enumerate(node_trace, start=1):
        node = step.get("node", "")
        status = step.get("status", "")
        output_keys = ", ".join(step.get("output_keys", []))
        lines.append(f"| {index} | `{node}` | {status} | `{output_keys}` |")

    lines.extend(["", "## Metrics", "", "| Metric | Value |", "| --- | --- |"])
    for key, value in metrics.items():
        if key == "dimension_scores" and isinstance(value, dict):
            lines.append(f"| `{key}` | `{_sanitize_secret_text(json_like(value))}` |")
        else:
            lines.append(f"| `{key}` | `{_sanitize_secret_text(value)}` |")

    return "\n".join(lines) + "\n"


def json_like(value: dict[str, Any]) -> str:
    return ", ".join(f"{key}: {item}" for key, item in value.items())
